name: Hello GITHUB
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-cicd-github-actions-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
    steps:
      - run: echo "Hello GITHUB!"
      - run: echo "GitHub actions hook running"
      - run: echo "GitHub and Codebuild connected"
