name: Hello WORLD & GITHUB 
on: [push]
jobs:  
  Hello-GIT-Job:
    runs-on: codebuild-cicd-github-connection-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
    steps:
      - run: echo "Hello GITHUB!!"
      - run: echo "GitHub actions hook running"
      - run: echo "GitHub and Codebuild connected"
